@url = http://localhost:7070/api
@userToken = b5b73fae0d87d8b4e2573105f8fbe7bc
@adminToken = c87295742b4e578cbd830b91acdcc9a7

###

# Get all exists tasks
# Tasks without test cases

GET {{url}}/tasks
Authorization: {{userToken}}

###

# Get tasks by lecture id
# Tasks without test cases

# * lecture - id of lecture

GET {{url}}/tasks?lecture=1
Authorization: {{userToken}}

###

# Get task details by id
# Includes tests cases

GET {{url}}/tasks/2
Authorization: {{userToken}}

###

# Create new task for lecture with lectureId
# [!] admin required
POST {{url}}/tasks
Authorization: {{adminToken}}
Content-Type: application/json

{
    "name": "Summ of #2",
    "description": "Summ of two number",
    "content": "input two a and b numbers and return summ of those numbers",
    "cases": [
        {
            "name": "Simple numbers",
            "input": "{ a: 10, b: 25 }",
            "expect": "35"
        }
    ],
    "lectureId": 1
}


###

# Update exists task by id
# [!] endpoint removes old task cases and add new
# [!] admin required

PUT {{url}}/tasks/2
Authorization: {{adminToken}}
Content-Type: application/json

{
    "name": "Division of #3",
    "description": "Division of two number",
    "content": "input two a and b numbers and return division of those numbers",
    "cases": [
        {
            "name": "Simple numbers",
            "input": "{ a: 125, b: 5 }",
            "expect": "25"
        }
    ],
    "lectureId": 1
}

###

# Delete exists task by id
# [!] endpoint removes task and test cases
# [!] admin required

DELETE {{url}}/tasks/3
Authorization: {{adminToken}}