GET http://localhost:7070/api/lectures
Authorization: c87295742b4e578cbd830b91acdcc9a7

###

POST http://localhost:7070/api/lectures
Authorization: c87295742b4e578cbd830b91acdcc9a7
Content-Type: application/json

{
    "name": "Javascript Intro",
    "content": "When to use JSONPlaceholder is a free online REST API that you can use whenever you need some fake data. It can be in a README on GitHub, for a demo on CodeSandbox, in code examples on Stack Overflow, ...or simply to test things locally."
}